apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "free5gc-pcf.fullname" . }}-config
  labels:
    {{- include "free5gc-pcf.labels" . | nindent 4 }}
data:

  pcfcfg.conf: |
    info:
      version: 1.0.0
      description: PCF initial local configuration

    {{- with .Values.pcfConfiguration }}
    configuration:
      pcfName: PCF
      sbi:
        scheme: {{ .sbi.scheme | default "http" | quote }}
        registerIPv4: {{ .sbi.serviceAddr | quote }}
        bindingIPv4: {{ .sbi.bindingAddr | default "0.0.0.0" | quote }}
        port: {{ .sbi.port | default 29507 }}
      timeFormat: {{ .timeFormat | default "2019-01-2 12:34:56" }}
      defaultBdtRefId: {{ .defaultBdtRef | default "BdtPolicyId-" }}
      nrfUri: {{ .nrf.scheme }}://{{ .nrf.serviceAddr }}:{{ .nrf.port }}
      serviceList:
      {{- range $key, $service := .supportedServices }}
        - serviceName: {{ $service.name }}
          {{- if $service.suppFeat }}
          suppFeat: {{ $service.suppFeat }}
          {{- else -}}
          {{- end }}
      {{- end }}
  {{- end }}

  free5GC.conf: |
    db_uri: mongodb://f5gc-mongodb:27017/free5gc

    #all logging levels
    #panic
    #fatal
    #error
    #warn
    #debug
    #debug
    #trace
    logger:
    # network function
      AMF:
        debugLevel: debug
        ReportCaller: true
      SMF:
        debugLevel: debug
        ReportCaller: true
      UDR:
        debugLevel: debug
        ReportCaller: true
      UDM:
        debugLevel: debug
        ReportCaller: true
      NRF:
        debugLevel: debug
        ReportCaller: true
      PCF:
        debugLevel: debug
        ReportCaller: true
      AUSF:
        debugLevel: debug
        ReportCaller: true
      N3IWF:
        debugLevel: debug
        ReportCaller: true
    # library
      NAS:
        debugLevel: debug
        ReportCaller: true
      FSM:
        debugLevel: debug
        ReportCaller: true
      NGAP:
        debugLevel: debug
        ReportCaller: true
      NamfComm:
        debugLevel: debug
        ReportCaller: true
      NamfEventExposure:
        debugLevel: debug
        ReportCaller: true
      NsmfPDUSession:
        debugLevel: debug
        ReportCaller: true
      NudrDataRepository:
        debugLevel: debug
        ReportCaller: true
      OpenApi:
        debugLevel: debug
        ReportCaller: true
      Aper:
        debugLevel: debug
        ReportCaller: true
      CommonConsumerTest:
        debugLevel: debug
        ReportCaller: true
    # webui
      WEBUI:
        debugLevel: debug
        ReportCaller: true
