apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "free5gc-webconsole.fullname" . }}-config
  labels:
    {{- include "free5gc-webconsole.labels" . | nindent 4 }}
data:
  webuicfg.conf: |
    info:
      version: 1.0.0
      description: WebUI Initial Local configuration

    configuration:
      mongodb:
        {{- with .Values.globalConfiguration.mongodb }}
        name: {{ .name | default "free5gc" }}
        url: {{ .url | lower }}
        {{- end }}
