apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5gc-nssf
  labels:
    app: f5gc-nssf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5gc-nssf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: f5gc-nssf
      annotations:
        k8s.v1.cni.cncf.io/networks: nssf-net1
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: nssf
          image: sumichaaan/f5gc-nssf:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - name: nssfcfg
              mountPath: /opt/f5gc/etc
            - name: free5gccfg
              mountPath: /opt/config
            - name: certs
              mountPath: /opt/support/TLS
          ports:
            - containerPort: 29531
              name: f5gc-nssf
              protocol: TCP
        - name: tcpdump
          image: corfr/tcpdump
          command:
            - /bin/sleep
            - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: nssf-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: certs
          secret:
            secretName: nssf-tls-secret
        - name: nssfcfg
          configMap:
            name: nssf-config
            items:
            - key: nssfcfg.conf
              path: nssfcfg.conf
        - name: free5gccfg
          configMap:
            name: nssf-config
            items:
            - key: free5GC.conf
              path: free5GC.conf
