resources:
  - 00_nssf-sa.yaml
  - 01_nssf-rbac.yaml
  - 02_nssf-configmap.yaml
  - 03_nssf-service.yaml
  - 04_nssf-deployment.yaml

namespace: free5gc

secretGenerator:
- name: f5gc-nssf-tls-secret
  namespace: default
  files:
  - cert/nssf.pem
  - cert/nssf.key
  type: "Opaque"
generatorOptions:
  disableNameSuffixHash: true
