apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5gc-nrf
  labels:
    app: f5gc-nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5gc-nrf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: f5gc-nrf
      annotations:
        k8s.v1.cni.cncf.io/networks: nrf-net1, nrf-net2
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: nrf
          image: sumichaaan/f5gc-nrf:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - name: certs
              mountPath: /opt/f5gc-nrf/certs
          ports:
            - containerPort: 29510
              name: f5gc-nrf
          env:
            - name: MONGODB_IP
              valueFrom:
                configMapKeyRef:
                  name: nrf-config
                  key: mongodb_ip
        - name: tcpdump
          image: corfr/tcpdump
          command:
            - /bin/sleep
            - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: nrf-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: certs
          secret:
            secretName: nrf-tls-secret
