resources:
  - 00_nrf-sa.yaml
  - 01_nrf-rbac.yaml
  - 02_configmap.yaml
  - 03_service.yaml
#  - 04_multus.yaml
  - 05_deployment.yaml

namespace: nrpj

secretGenerator:
- name: nrf-tls-secret
  namespace: default
  files:
  - certs/nrf.pem
  - certs/nrf.key
  type: "Opaque"
generatorOptions:
  disableNameSuffixHash: true
