apiVersion: v1
kind: Service
metadata:
  # name: {{ include "free5gc-nssf.fullname" . }}
  name: free5gc-nssf
  labels:
    {{- include "free5gc-nssf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.sbi.type }}
  ports:
    - port: {{ .Values.services.sbi.port }}
      targetPort: {{ .Values.nssfConfiguration.sbi.port }}
      protocol: TCP
      name: sbi
  selector:
    {{- include "free5gc-nssf.selectorLabels" . | nindent 4 }}
