resources:
  - 00_udm-sa.yaml
  - 01_udm-rbac.yaml
  - 02_configmap.yaml
  - 03_service.yaml
#  - 04_multus.yaml
  - 05_deployment.yaml

namespace: f5gc

secretGenerator:
- name: udm-tls-secret
  namespace: default
  files:
  - certs/udm.pem
  - certs/udm.key
  type: "Opaque"
generatorOptions:
  disableNameSuffixHash: true
