resources:
  - 00_amf-sa.yaml
  - 01_amf-rbac.yaml
  - 02_configmap.yaml
  - 03_service.yaml
#  - 04_multus.yaml
  - 05_deployment.yaml

namespace: f5gc

secretGenerator:
- name: amf-tls-secret
  namespace: default
  files:
  - certs/amf.pem
  - certs/amf.key
  type: "Opaque"
generatorOptions:
  disableNameSuffixHash: true
