---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: f5gc-mongodb
  name: f5gc-mongodb-headless
spec:
  clusterIP: None
  ports:
  - port: 27017
  selector:
    app: f5gc-mongodb

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: f5gc-mongodb
  name: f5gc-mongodb-nodeport
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: f5gc-mongodb
