apiVersion: v1
kind: Service
metadata:
  name: {{ include "free5gc-udm.fullname" . }}
  labels:
    {{- include "free5gc-udm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "free5gc-udm.selectorLabels" . | nindent 4 }}
